apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-api
spec:
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      app: category-api-app
  template:
    metadata:
      labels:
        app: category-api-app
    spec:
      containers:
        - name: rahadian
          image: swr.ap-southeast-3.myhuaweicloud.com/sonar-test/category-api:be4eb99be1248704f6b09f0eb39541bd0ce3034d
          ports:
            - containerPort: 3000
          env:
            - name: _ENV_DEPLOY
              value: develop
          resources:
            limits:
              memory: "256Mi"
              cpu: "128m"
      imagePullSecrets:
        - name: regcred
            

---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-category-api
  annotations:   
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: '{
      "type":"public",
      "bandwidth_name":"cce-bandwidth",
      "bandwidth_chargemode":"traffic",
      "bandwidth_size":2,
      "bandwidth_sharetype":"PER",
      "eip_type":"5_bgp",
      "name":"lb-category-api"}'
spec:
  type: LoadBalancer
  selector:
    app: category-api-app
  ports:
  - port: 80
    targetPort: 3000
